@baseUrl = http://localhost:3000/api
@accessToken = {{login.response.body.$.accessToken}}
@refreshToken = {{login.response.body.$.refreshToken}}
@userId = {{newUser.response.body.$.id}}

# Create a new Coach
# @name newUser
POST {{baseUrl}}/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Spartan Spartanych",
  "email": "sparta@gmail.com",
  "password": "123456",
  "role": "coach",
  "dateBirth": "2022-02-22",
  "gender": "male",
  "location": "Udelnaya",
  "level": "amateur",
  "workoutType": "boxing",
  "certificate": "certificate1.pdf"
}

###

# Login user by email and password
# @name login
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "sparta@gmail.com",
  "password": "123456"
}

###

# Get user by ID
GET {{baseUrl}}/auth/{{userId}} HTTP/1.1
Authorization: Bearer {{accessToken}}

###

# Get new JWT pair
POST {{baseUrl}}/auth/refresh HTTP/1.1
Authorization: Bearer {{refreshToken}}

###


###

# Update user data
PATCH {{baseUrl}}/auth/{{userId}} HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Dinam Dinamych"
}

###

# Check user token
POST {{baseUrl}}/auth/check HTTP/1.1
Authorization: Bearer {{accessToken}}

###
