@baseUrl = http://localhost:3000/api
@accessToken = {{login.response.body.$.accessToken}}
@refreshToken = {{login.response.body.$.refreshToken}}
@userId = {{newUser.response.body.$.id}}

# Create a new Coach
# @name newUser
POST {{baseUrl}}/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "Spartan Spartanych",
  "email": "spartanec@gmail.com",
  "password": "123456",
  "role": "User",
  "dateBirth": "2022-02-22",
  "gender": "Male",
  "location": "Udelnaya",
  "level": "Beginner",
  "workoutType": "Boxing",
  "certificate": "certificate1.pdf",
  "isReadyToTrain": true
}

###

# Login user by email and password
# @name login
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "sparta@gmail.com",
  "password": "123456"
}

###

# Get user by ID
GET {{baseUrl}}/auth/{{userId}} HTTP/1.1
Authorization: Bearer {{accessToken}}

###

# Get users
GET {{baseUrl}}/auth?level=amateur&location=Udelnaya HTTP/1.1

###

# Get new JWT pair
POST {{baseUrl}}/auth/refresh HTTP/1.1
Authorization: Bearer {{refreshToken}}

###

# Update user data
PATCH {{baseUrl}}/auth/{{userId}} HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "name": "Dinam Dinamych"
}

###

# Check user token
POST {{baseUrl}}/auth/check HTTP/1.1
Authorization: Bearer {{accessToken}}

###

# Add friend
PATCH {{baseUrl}}/auth/{{userId}}/friends/add HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "friendId": ""
}

###

# Remove friend
PATCH {{baseUrl}}/auth/{{userId}}/friends/remove HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "friendId": ""
}

###

# Add workouts to user balance
PATCH {{baseUrl}}/auth/{{userId}}/balance/add HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "workoutId": 1,
  "workoutNumber": 5
}

###

# Subtract workout to user balance
PATCH {{baseUrl}}/auth/{{userId}}/balance/sub HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "workoutId": 1
}

###

# Delete notifications
PATCH {{baseUrl}}/auth/{{userId}}/friends/remove HTTP/1.1
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "friendId": ""
}

###